#name of the branch
name: Building Incredible Docker Files

# condition when to excute
on:
  push:
    branches:
      - "master"
      - "dev"
      - "qa"

# Global Environments
env:
  CI: false
  REGISTRY: chrisedrego
  IMAGENAME: lite-alpine
  TAG: v1
  USERNAME: chrisedrego


# Jobs
jobs:
  build_deploy:
    runs-on: ubuntu-latest

# Stages AKA steps
    steps:
      - uses: actions/checkout@v2

      - name: Authentication
        shell: bash
        run: |
          docker login -u ${USERNAME} -p ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build
        shell: bash
        run: |
          cd ./dummy/   
          docker build --pull -t ${REGISTRY}/${IMAGENAME}:${TAG} -t ${REGISTRY}/${IMAGENAME} . 
                    
      - name: Push
        shell: bash
        run: |          
          docker push ${REGISTRY}/${IMAGENAME}:${TAG} && docker push ${REGISTRY}/${IMAGENAME}
          docker images

      - name: Run Me Any How
        shell: bash
        run: |
          echo "Imma gonna run anyhow bitch"