kind: Pod
apiVersion: v1
metadata:
  name: ubuntu
  namespace: monitor
spec:
  containers:
    - name: ubuntuc
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      ports:
        - containerPort: 9090
          name: web
        - containerPort: 9100
          name: node
  restartPolicy: Never